//Contains all the test data to be used in the suite

module.exports = {
    //user's username and password
    ausername: "alice",
    apassword: "wonderland",
    jusername: "john",
    jpassword: "doe",
    busername: "bob",
    bpassword: "bob",
    eusername: "emma",
    epassword: "emma",
    beusername: "becca",
    bepassword: "becca",
    pusername: "paul",
    ppassword: "paul",

    //alice's credit debit best match expected data
    a_user: "alice",
    a_cc_1_bankName: "Barclays",
    a_cc_1_accountType: "M",
    a_cc_1_accountTitle: "2 Years Fixed Reward",
    a_cc_1_totalBalanceDue: 800,
    a_cc_1_totalOutstandingBalance: 0,
    a_dc_1_1_bankName: "HSBC",
    a_dc_1_1_accountType: "PCA",
    a_dc_1_1_accountTitle: "HSBC Advance Bank Account",
    a_dc_1_1_contributingAmount: 800,
    a_dc_1_1_totalAvailableBalance: 2600,
    a_dc_1_1_interestRate: 0.1,

    a_cc_2_bankName: "NatWest",
    a_cc_2_accountType: "CC",
    a_cc_2_accountTitle: "Reward Black Credit Card",
    a_cc_2_totalBalanceDue: 1800,
    a_cc_2_apr: 37.1,
    a_cc_2_totalOutstandingBalance: 0,
    a_dc_2_1_bankName: "HSBC",
    a_dc_2_1_accountType: "PCA",
    a_dc_2_1_accountTitle: "HSBC Advance Bank Account",
    a_dc_2_1_contributingAmount: 1800,
    a_dc_2_1_totalAvailableBalance: 2600,
    a_dc_2_1_interestRate: 0.1,

    a_cc_3_bankName: "RBS",
    a_cc_3_accountType: "CC",
    a_cc_3_accountTitle: "RBS Unlimited Credit Card",
    a_cc_3_totalBalanceDue: 1200,
    a_cc_3_apr: 19.94,
    a_cc_3_totalOutstandingBalance: 0,
    a_dc_3_1_bankName: "Halifax",
    a_dc_3_1_accountType: "SB",
    a_dc_3_1_accountTitle: "Every Day Saver",
    a_dc_3_1_contributingAmount: 1000,
    a_dc_3_1_totalAvailableBalance: 1000,
    a_dc_3_1_interestRate: 0.2,
    a_dc_3_2_bankName: "Barclays",
    a_dc_3_2_accountType: "SB",
    a_dc_3_2_accountTitle: "Easy Saver",
    a_dc_3_2_contributingAmount: 200,
    a_dc_3_2_totalAvailableBalance: 5000,
    a_dc_3_2_interestRate: 0.25,

    //john's credit debit best match expected data
    j_user: "john",
    j_cc_1_bankName: "Barclays",
    j_cc_1_accountType: "M",
    j_cc_1_accountTitle: "2 Years Fixed Reward",
    j_cc_1_totalBalanceDue: 800,
    j_cc_1_interestRate: 3.3,
    j_cc_1_totalOutstandingBalance: 0,
    j_dc_1_1_bankName: "HSBC",
    j_dc_1_1_accountTitle: "HSBC Advance Bank Account",
    j_dc_1_1_contributingAmount: 800,
    j_dc_1_1_totalAvailableBalance: 2700,
    j_dc_1_1_interestRate: 0.1,

    j_cc_2_bankName: "RBS",
    j_cc_2_accountType: "CC",
    j_cc_2_accountTitle: "Classic Credit Card",
    j_cc_2_totalBalanceDue: 2000,
    j_cc_2_apr: 27.1,
    j_cc_2_totalOutstandingBalance: 0,
    j_dc_2_1_bankName: "HSBC",
    j_dc_2_1_accountTitle: "HSBC Advance Bank Account",
    j_dc_2_1_contributingAmount: 1900,
    j_dc_2_1_totalAvailableBalance: 2700,
    j_dc_2_1_interestRate: 0.1,
    j_dc_2_2_bankName: "Halifax",
    j_dc_2_2_accountType: "SB",
    j_dc_2_2_accountTitle: "Every Day Saver",
    j_dc_2_2_contributingAmount: 100,
    j_dc_2_2_totalAvailableBalance: 1900,
    j_dc_2_2_interestRate: 0.2,

    j_cc_3_bankName: "NatWest",
    j_cc_3_accountType: "CC",
    j_cc_3_accountTitle: "Reward Black Credit Card",
    j_cc_3_totalBalanceDue: 2900,
    j_cc_3_apr: 23.7,
    j_cc_3_totalOutstandingBalance: 900,
    j_dc_3_1_bankName: "Halifax",
    j_dc_3_1_accountType: "SB",
    j_dc_3_1_accountTitle: "Every Day Saver",
    j_dc_3_1_contributingAmount: 1800,
    j_dc_3_1_totalAvailableBalance: 1900,
    j_dc_3_1_interestRate: 0.2,
    j_dc_3_2_bankName: "Barclays",
    j_dc_3_2_accountType: "SB",
    j_dc_3_2_accountTitle: "Easy Saver",
    j_dc_3_2_contributingAmount: 200,
    j_dc_3_2_totalAvailableBalance: 200,
    j_dc_3_2_interestRate: 0.25,

    //emma's credit debit best match expected data
    e_user: "emma",
    e_cc_1_bankName: "RBS",
    e_cc_1_accountType: "CC",
    e_cc_1_accountTitle: "RBS Unlimited Credit Card",
    e_cc_1_totalBalanceDue: 500,
    e_cc_1_apr: 19.94,
    e_cc_1_totalOutstandingBalance: 0,
    e_dc_1_bankName: "HSBC",
    e_dc_1_accountType: "PCA",
    e_dc_1_accountTitle: "HSBC Advance Bank Account",
    e_dc_1_contributingAmount: 500,
    e_dc_1_totalAvailableBalance: 1000,
    e_dc_1_interestRate: 0.1,

    e_cc_2_bankName: "NatWest",
    e_cc_2_accountType: "CC",
    e_cc_2_accountTitle: "Reward Black Credit Card",
    e_cc_2_totalBalanceDue: 2000,
    e_cc_2_apr: 37.1,
    e_cc_2_totalOutstandingBalance: 0,
    e_dc_2_bankName: "Halifax",
    e_dc_2_accountType: "SB",
    e_dc_2_accountTitle: "Every Day Saver",
    e_dc_2_contributingAmount: 2000,
    e_dc_2_totalAvailableBalance: 4000,
    e_dc_2_interestRate: 0.2,

    e_cc_3_bankName: "Barclays",
    e_cc_3_accountType: "M",
    e_cc_3_accountTitle: "2 Years Fixed Reward",
    e_cc_3_totalBalanceDue: 500,
    e_cc_3_interestRate: 3.3,
    e_cc_3_minMonthlyPayment: 500,
    e_cc_3_totalOutstandingBalance: 0,
    e_dc_3_bankName: "HSBC",
    e_dc_3_accountType: "PCA",
    e_dc_3_accountTitle: "HSBC Advance Bank Account",
    e_dc_3_contributingAmount: 500,
    e_dc_3_totalAvailableBalance: 1000,
    e_dc_3_interestRate: 0.1,

    //paul's credit debit best match expected data
    p_user: "paul",
    p_cc_1_bankName: "Mongo",
    p_cc_1_accountType: "CC",
    p_cc_1_accountTitle: "RBS Unlimited Credit Card",
    p_cc_1_totalBalanceDue: 800,
    p_cc_1_apr: 20,
    p_cc_1_minimumDue: 100,
    p_cc_1_totalOutstandingBalance: 0,
    p_dc_1_bankName: "HSBC",
    p_dc_1_accountType: "PCA",
    p_dc_1_accountTitle: "HSBC Advance Bank Account",
    p_dc_1_contributingAmount: 800,
    p_dc_1_totalAvailableBalance: 1000,
    p_dc_1_interestRate: 0.1,

    p_cc_2_bankName: "RBS",
    p_cc_2_accountType: "CC",
    p_cc_2_accountTitle: "RBS Unlimited Credit Card",
    p_cc_2_totalBalanceDue: 800,
    p_cc_2_apr: 20,
    p_cc_2_minimumDue: 100,
    p_cc_2_totalOutstandingBalance: 0,
    p_dc_2_bankName: "Halifax",
    p_dc_2_accountType: "SB",
    p_dc_2_accountTitle: "Every Day Saver",
    p_dc_2_contributingAmount: 800,
    p_dc_2_totalAvailableBalance: 1000,
    p_dc_2_interestRate: 0.1,

    p_cc_3_bankName: "Barclays",
    p_cc_3_accountType: "M",
    p_cc_3_accountTitle: "2 Years Fixed Reward",
    p_cc_3_totalBalanceDue: 100,
    p_cc_3_interestRate: 20,
    p_cc_3_minMonthlyPayment: 100,
    p_cc_3_totalOutstandingBalance: 0,
    p_dc_3_bankName: "HSBC",
    p_dc_3_accountType: "PCA",
    p_dc_3_accountTitle: "HSBC Advance Bank Account",
    p_dc_3_contributingAmount: 100,
    p_dc_3_totalAvailableBalance: 1000,
    p_dc_3_interestRate: 0.1,

    //becca's credit debit best match expected data
    be_user: "becca",
    be_cc_1_bankName: "Barclays",
    be_cc_1_accountType: "M",
    be_cc_1_accountTitle: "2 Years Fixed Reward",
    be_cc_1_totalBalanceDue: 200,
    be_cc_1_interestRate: 3.3,
    be_cc_1_minMonthlyPayment: 200,
    be_cc_1_totalOutstandingBalance: 0,
    be_dc_1_bankName: "Barclays",
    be_dc_1_accountType: "SB",
    be_dc_1_accountTitle: "Easy Saver",
    be_dc_1_contributingAmount: 200,
    be_dc_1_totalAvailableBalance: 300,
    be_dc_1_interestRate: 0.25,

    be_cc_2_bankName: "RBS",
    be_cc_2_accountType: "CC",
    be_cc_2_accountTitle: "RBS Unlimited Credit Card",
    be_cc_2_totalBalanceDue: 500,
    be_cc_2_apr: 19.94,
    be_cc_2_minimumDue: 100,
    be_cc_2_totalOutstandingBalance: 0,
    be_dc_2_bankName: "Halifax",
    be_dc_2_accountType: "SB",
    be_dc_2_accountTitle: "Every Day Saver",
    be_dc_2_contributingAmount: 500,
    be_dc_2_totalAvailableBalance: 500,
    be_dc_2_interestRate: 0.2,

    be_cc_3_bankName: "NatWest",
    be_cc_3_accountType: "CC",
    be_cc_3_accountTitle: "Reward Black Credit Card",
    be_cc_3_totalBalanceDue: 1000,
    be_cc_3_apr: 37.1,
    be_cc_3_minimumDue: 300,
    be_cc_3_totalOutstandingBalance: 0,
    be_dc_3_bankName: "HSBC",
    be_dc_3_accountType: "PCA",
    be_dc_3_accountTitle: "HSBC Advance Bank Account",
    be_dc_3_contributingAmount: 1000,
    be_dc_3_totalAvailableBalance: 1000,
    be_dc_3_interestRate: 0.1,

    //bob's credit debit best match expected data
    b_user: "bob",
    b_cc_1_bankName: "RBS",
    b_cc_1_accountType: "CC",
    b_cc_1_accountTitle: "RBS Unlimited Credit Card",
    b_cc_1_totalBalanceDue: 500,
    b_cc_1_apr: 19.94,
    b_cc_1_minimumDue: 100,
    b_cc_1_totalOutstandingBalance: 300,
    b_dc_1_bankName: "Barclays",
    b_dc_1_accountType: "SB",
    b_dc_1_accountTitle: "Easy Saver",
    b_dc_1_contributingAmount: 200,
    b_dc_1_totalAvailableBalance: 500,
    b_dc_1_interestRate: 0.25,

    b_cc_2_bankName: "NatWest",
    b_cc_2_accountType: "CC",
    b_cc_2_accountTitle: "Reward Black Credit Card",
    b_cc_2_totalBalanceDue: 1000,
    b_cc_2_apr: 37.1,
    b_cc_2_minimumDue: 300,
    b_cc_2_totalOutstandingBalance: 0,
    b_dc_2_bankName: "HSBC",
    b_dc_2_accountType: "PCA",
    b_dc_2_accountTitle: "HSBC Advance Bank Account",
    b_dc_2_contributingAmount: 1000,
    b_dc_2_totalAvailableBalance: 1000,
    b_dc_2_interestRate: 0.1,

    b_cc_3_bankName: "Barclays",
    b_cc_3_accountType: "M",
    b_cc_3_accountTitle: "2 Years Fixed Reward",
    b_cc_3_totalBalanceDue: 200,
    b_cc_3_interestRate: 3.3,
    b_cc_3_minMonthlyPayment: 200,
    b_cc_3_totalOutstandingBalance: 0,
    b_dc_3_bankName: "Barclays",
    b_dc_3_accountType: "SB",
    b_dc_3_accountTitle: "Easy Saver",
    b_dc_3_contributingAmount: 200,
    b_dc_3_totalAvailableBalance: 500,
    b_dc_3_interestRate: 0.25,

    b_cc_4_bankName: "Mongo",
    b_cc_4_accountType: "CC",
    b_cc_4_accountTitle: "RBS Unlimited Credit Card",
    b_cc_4_totalBalanceDue: 400,
    b_cc_4_apr: 18.94,
    b_cc_4_minimumDue: 100,
    b_cc_4_totalOutstandingBalance: 300,
    b_dc_4_bankName: "Barclays",
    b_dc_4_accountType: "SB",
    b_dc_4_accountTitle: "Easy Saver",
    b_dc_4_contributingAmount: 100,
    b_dc_4_totalAvailableBalance: 500,
    b_dc_4_interestRate: 0.25

};
